Milestone 5 - Create model with associations and all requested features for friendships.
RyelBanfield/ror-social-scaffold pull request #2
Opened 2021-04-19 15:46 UTC by RyelBanfield

In this milestone, I created and tested everything needed for a working version of the friendship feature. I did no styling as all that is needed is for the feature to work.

2021-04-19 19:33 UTC, cyonii requested changes
### STATUS: CHANGES REQUIRED ♻️✍️

Hello @RyelBanfield, you have shown a great effort and energy so far. 

#### TO HIGHLIGHT
- Simple and good PR description
- Nice job implementing the friendship concept
- Good job adding integration and unit tests, and getting them all passing. It is a great way to reduce bugs in apps, I applaud you.
- Nice to validate data
- Superb job keeping logic away from view, you don't see this every day.

#### TO IMPROVE
- [x] User model should `has_many :friendships` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/friend.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
- [ ] Post timeline should contain posts authored by the logged-in user and their friends. Right now I can see posts from people I'm not friends with. Please fix this.
```ruby
# User model

def friends_and_own_posts
  Post.where(user: (self.friends.to_a << self))
  # This will produce SQL query with IN. Something like: select * from posts where user_id IN (1,45,874,43);
end
```
- [ ] Great job there with RSpec but your tests didn't cover validations. Please include validation tests for your models. Too-careful never spoiled anything.

#### NICE TO HAVE
Please note that these are optional suggestions which means they're not mandatory.
- [ ] It would be nice to have the **Accept** and **Reject** friendship buttons right beside the user in the `User#index` show. And inform the user that they're already friends, or that their requests are pending in such cases.
- [ ] I see you have renamed the associations, It would be nice to name your associations as recommended by the project's specifications for simplicity.

> ##### IMPORTANT NOTICE ⚠️
> You have implemented the concepts of friendship v2, which is in the scope of the next milestone (6), great job. Please note that this review focuses on the scope of friendship v1. Remember to provide a link(s) to specific commits in order to inform the next reviewer of these implementations.


#### <br>You can ping me on Slack @[CY Kalu](https://microverse-students.slack.com/team/U01494U96FR) to draw my attention in case I do not respond quickly on here. I'm always available and will be glad to help.<br><br>

2021-04-19 19:33 UTC, cyonii commented on app/controllers/friendships_controller.rb
> +  def accept_friend
- [ ] [OPTIONAL] It would be great to maintain Rail's REST convention of naming controller actions and URLs. For example, the `#update` action would be suited for this.

2021-04-19 19:33 UTC, cyonii commented on app/controllers/friendships_controller.rb
> +  def decline_friend
- [ ] [OPTIONAL] Following RESTful convention, you could use `#destroy` method for this action.

2021-04-20 10:55 UTC, RyelBanfield commented
Thank you for your review. I have noted the optional changes and will definitely keep them in mind while implementing the features I have learnt into my own personal side project which is hosted here if you are interested - https://netflix-trackr.herokuapp.com/

You said to add `has_many :friendships` to my user model but it seems to break when I do that and I'm not sure why however as far as I can see it all works perfectly the way I did it. Let me know your thoughts on that.

2021-04-20 11:17 UTC, umairarshadbutt requested changes
# Status: REQUIRED CHANGES :warning: :construction: 

Hi @RyelBanfield 
Such a remarkable project you made :+1: ! Awesome README :100: !
Good job with the changes! :tada: We are almost there.
We, however, do have a few changes to carry out before we proceed.

##

Kindly work on the suggested changes  👇.
- [x] Please work on the previous code reviewer suggestion because it is a requirement. User model should has_many :friendships ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/friend.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))

##
- **When you have made the specified changes, please submit another code review. Thank you!**
##
**If you are stuck at any point or have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help**
HAPPY CODING :computer:
**[Umair Arshad (Code Reviewer)](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

2021-04-20 12:13 UTC, umairarshadbutt approved these changes
# **Status: PROJECT APPROVED** :champagne:
Excellent job on this project guys. :fireworks: Keep it up.
##
**All the required tasks have been fulfilled in this project. I will go ahead and mark this as complete.**
- Congratulations on the splendid job @RyelBanfield ! :+1: 
- You can now merge to master and submit the project completion form :rocket: . I wish you all the very best in your next tasks :1st_place_medal:
##
HAPPY CODING :computer:
**[Umair Arshad (Code Reviewer)](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

2021-04-20 12:17 UTC, RyelBanfield commented
Thank you!

2021-04-20 12:19 UTC, merged

2021-04-20 13:10 UTC, cyonii commented
> Thank you for your review. I have noted the optional changes and will definitely keep them in mind while implementing the features I have learnt into my own personal side project which is hosted here if you are interested - https://netflix-trackr.herokuapp.com/
> 
> 
> 
> You said to add `has_many :friendships` to my user model but it seems to break when I do that and I'm not sure why however as far as I can see it all works perfectly the way I did it. Let me know your thoughts on that.

Hey @RyelBanfield, your NetflixTrackr app is cool, the mobile view feels at home. I like the minimalistic UI 👌🏼.

##### Suggestion:
It'll be nice to have a text label beside the notification and user-settings icon on mobile view to improve user experience. I mean the spaces are free.
![image](https://user-images.githubusercontent.com/47994600/115400861-a7cee600-a1e1-11eb-92ee-35068f382c59.jpeg)

2021-04-20 13:48 UTC, RyelBanfield commented
@cyonii thanks man! Noted. :)